### ISSUE TITLE
info.prettyPrintTo(payload) triggers reboot

### ISSUE THREAD

**Issue by psy** [esper-hub/esper#16]
https://github.com/esper-hub/esper/blob/147dc9a26e58fe77e9450543740c88657d86a154/framework/services/Info.cpp#L106

triggers: 

```***** Software Watchdog Reset```

**Comment by mweinelt** [comment]
What environment did you use to build ESPer? Would you be able to retry this with the docker container after #23?

**Comment by fooker** [comment]
@psy: we've incorporated the fix mentioned by @mweinelt. Can you try again with latest docker container?

**Comment by mweinelt** [comment]
Closing this issue for lack of feedback.

If you have new feedback just add it and we'll reopen the issue. Until then we consider it obsolete, due to several Sming updates.
